### ISSUE TITLE
GraphicsEvents.OnPreRenderHudEvent

### ISSUE THREAD

**Issue by Apocalypso0** [jotser/StardewMods#6]
It crashes with ObjectProgressBar

[ObjectProgressBars] This mod failed in the GraphicsEvents.OnPreRenderHudEvent event. Technical details:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei ObjectProgressBars.ModEntry.Draw(Object sender, EventArgs args)
   bei StardewModdingAPI.Framework.Events.ManagedEvent.Raise() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:Zeile 126.

**Comment by jotser** [comment]
I believe the latest versions should have addressed this issue, Thanks :)
