### ISSUE TITLE
[Bug] No option to buy Auto-Grabber from Marnie?

### ISSUE THREAD

**Issue by cheesealmighty** [jotser/StardewMods#7]
I might be horribly failing but, using latest available version on the Nexus. 
And here's my modlist: https://puu.sh/C9MOr/2d9bf0a50e.png

Pressing "Z" prompts me to purchase an auto-grabber from Marnie. But Marnie's shop does not have it anywhere. Am I missing something?

Edit: After cheating the item, it seems fully functional. This is probably result of a mod interaction.

**Comment by paxchristos** [comment]
You need to be level 10 farming to purchase an Auto-Grabber. Most likely not a bug.

**Comment by cheesealmighty** [comment]
Oops. I didn't realize auto-grabbers were vanilla items. Been a while since I played. 

Yup. Not a bug at all.
